- class_name: 前端项目
  class_desc: 一些奇奇怪怪的小玩意
  project_list:
    - name: ISES
      custom: 即刻短文
      opinion: 即刻短文，一个随时随地即刻的短文分享平台
      details_flink: https://ises.bywind.xyz
      image: /images/我的项目/cover.webp
