- class_name: 前端项目
  class_desc: 一些奇奇怪怪的小玩意
  project_list:
    - name: Rdtf
      custom: 模板框架
      opinion: Rdtf是一个基于Next.js构建的快速开发模板旨在实现低代码量实现快速开发
      details_flink: https://dawsons.love
      image: /images/Rdtf基于Next.js构建的快速开发模板/cover.webp
